services:

  signoz:
    image: signoz/signoz-standalone:latest
    container_name: signoz
    privileged: true
    ports:
      - "8080:8080"   # SigNoz UI
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
    volumes:
      - signoz-clickhouse:/var/lib/clickhouse
      - signoz-data:/var/lib/signoz

volumes:
  signoz-clickhouse:
  signoz-data: