receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed

  file/traces:
    path: /var/log/otel/traces.json
    rotation:
      max_megabytes: 10
      max_days: 7
      max_backups: 3

  file/metrics:
    path: /var/log/otel/metrics.json
    rotation:
      max_megabytes: 10
      max_days: 7
      max_backups: 3

  file/logs:
    path: /var/log/otel/logs.json
    rotation:
      max_megabytes: 10
      max_days: 7
      max_backups: 3

  otlp/jaeger:
    endpoint: http://jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:  [otlp]
      exporters:  [debug, file/traces, otlp/jaeger]
    metrics:
      receivers:  [otlp]
      exporters:  [debug, file/metrics]
    logs:
      receivers:  [otlp]
      exporters:  [debug, file/logs]