// <auto-generated />
using AspNetCore10.OpenTelemetry.Study.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCore10.OpenTelemetry.Study.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AspNetCore10.OpenTelemetry.Study.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice.johnson@example.com",
                            Name = "Alice Johnson",
                            PhoneNumber = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob.smith@example.com",
                            Name = "Bob Smith",
                            PhoneNumber = "555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie.brown@example.com",
                            Name = "Charlie Brown",
                            PhoneNumber = "555-0103"
                        },
                        new
                        {
                            Id = 4,
                            Email = "diana.prince@example.com",
                            Name = "Diana Prince",
                            PhoneNumber = "555-0104"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ethan.hunt@example.com",
                            Name = "Ethan Hunt",
                            PhoneNumber = "555-0105"
                        },
                        new
                        {
                            Id = 6,
                            Email = "fiona.gallagher@example.com",
                            Name = "Fiona Gallagher",
                            PhoneNumber = "555-0106"
                        },
                        new
                        {
                            Id = 7,
                            Email = "george.costanza@example.com",
                            Name = "George Costanza",
                            PhoneNumber = "555-0107"
                        },
                        new
                        {
                            Id = 8,
                            Email = "hannah.abbott@example.com",
                            Name = "Hannah Abbott",
                            PhoneNumber = "555-0108"
                        },
                        new
                        {
                            Id = 9,
                            Email = "ian.malcolm@example.com",
                            Name = "Ian Malcolm",
                            PhoneNumber = "555-0109"
                        },
                        new
                        {
                            Id = 10,
                            Email = "jane.doe@example.com",
                            Name = "Jane Doe",
                            PhoneNumber = "555-0110"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
